# Generated by Django 2.2 on 2023-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_bok_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('AUTHOR', '1'), ('ADMIN', '2')], default='1', max_length=20),
        ),
    ]
