# Generated by Django 2.2 on 2023-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_bok_api', '0003_recipemenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('1', 'Author'), ('2', 'Admin')], default='1', max_length=20),
        ),
    ]
