# Generated by Django 2.2 on 2023-07-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_bok_api', '0006_auto_20230706_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemenu',
            old_name='user_role',
            new_name='user_profile',
        ),
    ]
