# Generated by Django 2.2 on 2023-07-06 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook_bok_api', '0007_auto_20230706_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemenu',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
